"""
This Veros setup file was generated by

   $ veros copy-setup global_4deg

on 2026-01-13 16:39:27 UTC.
"""

__VEROS_VERSION__ = "1.6.0"

if __name__ == "__main__":
    raise RuntimeError(
        f"Veros setups cannot be executed directly. Try `veros run {__file__}` instead."
    )

# -- end of auto-generated header, original file below --


import os

os.environ["VEROS_BACKEND"] = "jax"

import h5netcdf
import veros.tools
from veros import (
    KernelOutput,
    VerosSetup,
    logger,
    veros_kernel,
    veros_routine,
)

# runtime_settings.backend = "jax"
from veros.core.operators import at, update
from veros.core.operators import numpy as npx
from veros.variables import Variable

class GlobalFourDegreeSetup(VerosSetup):
    """Global 4 degree model with 15 vertical levels.

    This setup demonstrates:
     - setting up a realistic model
     - reading input data from external files
     - including Indonesian throughflow
     - implementing surface forcings
     - applying a simple ice mask

    `Adapted from pyOM2 <https://wiki.cen.uni-hamburg.de/ifm/TO/pyOM2/4x4%20global%20model>`_.

    ChangeLog
     - 07-05-2020: modify bathymetry in order to include Indonesian throughflow;
       courtesy of Franka Jesse, Utrecht University

    """

    def __init__(
        self,
        id,
        runlen,
        restart_name,
        snap_out_freq=86400 * 360,
        restart_mode=True,
        **kwargs,
    ):
        super().__init__(**kwargs)

        self.id = id
        self.runlen = runlen
        self.restart_mode = restart_mode
        self.restart_name = restart_name
        self.snap_out_freq = snap_out_freq

    @veros_routine
    def set_parameter(self, state):
        settings = state.settings

        settings.identifier = self.id
        settings.restart_input_filename = self.restart_name
        settings.description = (
            "Global 4 degree setup tailored for Anderson Acceleration"
        )

        settings.nx, settings.ny, settings.nz = 90, 40, 15
        settings.dt_mom = 1800.0
        settings.dt_tracer = 86400.0
        settings.runlen = self.runlen

        settings.x_origin = 4.0
        settings.y_origin = -76.0

        settings.coord_degree = True
        settings.enable_cyclic_x = True

        settings.enable_neutral_diffusion = True
        settings.K_iso_0 = 1000.0
        settings.K_iso_steep = 1000.0
        settings.iso_dslope = 4.0 / 1000.0
        settings.iso_slopec = 1.0 / 1000.0
        settings.enable_skew_diffusion = True

        settings.enable_hor_friction = True
        settings.A_h = (4 * settings.degtom) ** 3 * 2e-11
        settings.enable_hor_friction_cos_scaling = True
        settings.hor_friction_cosPower = 1

        settings.enable_implicit_vert_friction = True
        settings.enable_tke = True
        settings.c_k = 0.1
        settings.c_eps = 0.7
        settings.alpha_tke = 30.0
        settings.mxl_min = 1e-8
        settings.tke_mxl_choice = 2
        settings.kappaM_min = 2e-4
        settings.kappaH_min = 2e-5
        settings.enable_kappaH_profile = True
        settings.enable_tke_superbee_advection = True

        settings.enable_eke = True
        settings.eke_k_max = 1e4
        settings.eke_c_k = 0.4
        settings.eke_c_eps = 0.5
        settings.eke_cross = 2.0
        settings.eke_crhin = 1.0
        settings.eke_lmin = 100.0
        settings.enable_eke_superbee_advection = True

        settings.enable_idemix = False
        settings.enable_idemix_hor_diffusion = True
        settings.enable_eke_diss_surfbot = True
        settings.eke_diss_surfbot_frac = 0.2
        settings.enable_idemix_superbee_advection = True

        settings.enable_streamfunction = True
        settings.enable_TEM_friction = True

        settings.eq_of_state_type = 5

        # custom variables
        state.dimensions["nmonths"] = 1
        state.var_meta.update(
            sss_clim=Variable(
                "sss_clim", ("xt", "yt", "nmonths"), "", "", time_dependent=False
            ),
            sst_clim=Variable(
                "sst_clim", ("xt", "yt", "nmonths"), "", "", time_dependent=False
            ),
            qnec=Variable(
                "qnec", ("xt", "yt", "nmonths"), "", "", time_dependent=False
            ),
            qnet=Variable(
                "qnet", ("xt", "yt", "nmonths"), "", "", time_dependent=False
            ),
            taux=Variable(
                "taux", ("xt", "yt", "nmonths"), "", "", time_dependent=False
            ),
            tauy=Variable(
                "tauy", ("xt", "yt", "nmonths"), "", "", time_dependent=False
            ),
        )

    def _read_forcing(self, var):
        with h5netcdf.File("./forcing_4deg_global_annual_mean.nc", "r") as infile:
            var_obj = infile.variables[var]
            if var in ["q_net", "sst", "sss", "tau_x", "tau_y"]:
                return npx.array(var_obj)[npx.newaxis].T
            return npx.array(var_obj).T

    @veros_routine
    def set_grid(self, state):
        vs = state.variables
        ddz = npx.array(
            [
                50.0,
                70.0,
                100.0,
                140.0,
                190.0,
                240.0,
                290.0,
                340.0,
                390.0,
                440.0,
                490.0,
                540.0,
                590.0,
                640.0,
                690.0,
            ]
        )
        vs.dzt = ddz[::-1]
        vs.dxt = 4.0 * npx.ones_like(vs.dxt)
        vs.dyt = 4.0 * npx.ones_like(vs.dyt)

    @veros_routine
    def set_coriolis(self, state):
        vs = state.variables
        settings = state.settings
        vs.coriolis_t = update(
            vs.coriolis_t,
            at[...],
            2 * settings.omega * npx.sin(vs.yt[npx.newaxis, :] / 180.0 * settings.pi),
        )

    @veros_routine(dist_safe=False, local_variables=["kbot", "zt"])
    def set_topography(self, state):
        vs = state.variables
        settings = state.settings

        bathymetry_data = self._read_forcing("bathymetry")
        salt_data = self._read_forcing("salinity")[:, :, ::-1]
        land_mask = (
            vs.zt[npx.newaxis, npx.newaxis, :] <= bathymetry_data[..., npx.newaxis]
        ) | (salt_data == 0.0)

        vs.kbot = update(
            vs.kbot, at[2:-2, 2:-2], 1 + npx.sum(land_mask.astype("int"), axis=2)
        )

        # set all-land cells
        all_land_mask = (bathymetry_data == 0) | (vs.kbot[2:-2, 2:-2] == settings.nz)
        vs.kbot = update(
            vs.kbot, at[2:-2, 2:-2], npx.where(all_land_mask, 0, vs.kbot[2:-2, 2:-2])
        )

    @veros_routine(
        dist_safe=False,
        local_variables=[
            "taux",
            "tauy",
            "qnec",
            "qnet",
            "sss_clim",
            "sst_clim",
            "temp",
            "salt",
            "area_t",
            "maskT",
            "forc_iw_bottom",
            "forc_iw_surface",
        ],
    )
    def set_initial_conditions(self, state):
        vs = state.variables
        settings = state.settings

        # initial conditions for T and S
        temp_data = self._read_forcing("temperature")[:, :, ::-1]
        vs.temp = update(
            vs.temp,
            at[2:-2, 2:-2, :, :2],
            temp_data[:, :, :, npx.newaxis] * vs.maskT[2:-2, 2:-2, :, npx.newaxis],
        )

        salt_data = self._read_forcing("salinity")[:, :, ::-1]
        vs.salt = update(
            vs.salt,
            at[2:-2, 2:-2, :, :2],
            salt_data[..., npx.newaxis] * vs.maskT[2:-2, 2:-2, :, npx.newaxis],
        )

        # use Trenberth wind stress from MITgcm instead of ECMWF (also contained in ecmwf_4deg.cdf)
        vs.taux = update(vs.taux, at[2:-2, 2:-2, :], self._read_forcing("tau_x"))
        vs.tauy = update(vs.tauy, at[2:-2, 2:-2, :], self._read_forcing("tau_y"))

        # heat flux
        with h5netcdf.File("./ecmwf_4deg_monthly_nc4.nc", "r") as ecmwf_data:
            qnec_var = ecmwf_data.variables["Q3"]
            qnec_var = npx.array(qnec_var).mean(axis=0)[npx.newaxis].T
            vs.qnec = update(vs.qnec, at[2:-2, 2:-2, :], qnec_var)
            vs.qnec = npx.where(vs.qnec <= -1e10, 0.0, vs.qnec)

        q = self._read_forcing("q_net")
        vs.qnet = update(vs.qnet, at[2:-2, 2:-2, :], -q)
        vs.qnet = npx.where(vs.qnet <= -1e10, 0.0, vs.qnet)

        mean_flux = (
            npx.sum(vs.qnet[2:-2, 2:-2, :] * vs.area_t[2:-2, 2:-2, npx.newaxis])
            / npx.sum(vs.area_t[2:-2, 2:-2])

        )
        logger.info(
            " removing an annual mean heat flux imbalance of %e W/m^2" % mean_flux
        )
        vs.qnet = (vs.qnet - mean_flux) * vs.maskT[:, :, -1, npx.newaxis]

        # SST and SSS
        vs.sst_clim = update(vs.sst_clim, at[2:-2, 2:-2, :], self._read_forcing("sst"))
        vs.sss_clim = update(vs.sss_clim, at[2:-2, 2:-2, :], self._read_forcing("sss"))

        if settings.enable_idemix:
            vs.forc_iw_bottom = update(
                vs.forc_iw_bottom,
                at[2:-2, 2:-2],
                self._read_forcing("tidal_energy") / settings.rho_0,
            )
            vs.forc_iw_surface = update(
                vs.forc_iw_surface,
                at[2:-2, 2:-2],
                self._read_forcing("wind_energy") / settings.rho_0 * 0.2,
            )

    @veros_routine
    def set_forcing(self, state):
        vs = state.variables
        vs.update(set_forcing_kernel(state))

    @veros_routine
    def set_diagnostics(self, state):
        diagnostics = state.diagnostics

        snapshot_vars = ["temp", "salt", "u", "v", "prho"]

        diagnostics["snapshot"].output_variables = snapshot_vars
        diagnostics["snapshot"].output_frequency = self.snap_out_freq

        diagnostics["averages"].output_variables = snapshot_vars
        diagnostics["averages"].output_frequency = self.snap_out_freq
        diagnostics["averages"].sampling_frequency = 86400

    @veros_routine
    def after_timestep(self, state):
        pass


@veros_kernel
def set_forcing_kernel(state):
    vs = state.variables
    settings = state.settings

    vs.surface_taux = vs.taux[:, :, 0]
    vs.surface_tauy = vs.tauy[:, :, 0]

    # tke flux
    if settings.enable_tke:
        vs.forc_tke_surface = update(
            vs.forc_tke_surface,
            at[1:-1, 1:-1],
            npx.sqrt(
                (
                    0.5
                    * (vs.surface_taux[1:-1, 1:-1] + vs.surface_taux[:-2, 1:-1])
                    / settings.rho_0
                )
                ** 2
                + (
                    0.5
                    * (vs.surface_tauy[1:-1, 1:-1] + vs.surface_tauy[1:-1, :-2])
                    / settings.rho_0
                )
                ** 2
            )
            ** 1.5,
        )
    # heat flux : W/m^2 K kg/J m^3/kg = K m/s
    cp_0 = 3991.86795711963
    sst = vs.sst_clim[:, :, 0]
    qnec = vs.qnec[:, :, 0]
    qnet = vs.qnet[:, :, 0]

    vs.forc_temp_surface = (
        (qnet + qnec * (sst - vs.temp[:, :, -1, vs.tau]))
        * vs.maskT[:, :, -1]
        / cp_0
        / settings.rho_0
    )

    # apply simple ice mask
    mask = npx.logical_and(
        vs.temp[:, :, -1, vs.tau] * vs.maskT[:, :, -1] < -1.8,
        vs.forc_temp_surface < 0.0,
    )
    vs.forc_temp_surface = npx.where(mask, 0.0, vs.forc_temp_surface)

    return KernelOutput(
        surface_taux=vs.surface_taux,
        surface_tauy=vs.surface_tauy,
        forc_tke_surface=vs.forc_tke_surface,
        forc_temp_surface=vs.forc_temp_surface,
        forc_salt_surface=npx.zeros_like(vs.forc_temp_surface),
    )
